<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IndustrialFieldDataAcquisitionTerminal</RootNamespace>
    <AssemblyName>IndustrialFieldDataAcquisitionTerminal</AssemblyName>
    <ApplicationTitle>工业现场数据采集终端</ApplicationTitle>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="9.0.0" />
  </ItemGroup>
</Project>
