#ifndef BSP_DIGITAL_IO_H
#define BSP_DIGITAL_IO_H

#include <stdint.h>

#include "board_pins.h"

#ifndef BSP_DIGITAL_IO_INPUT_ACTIVE_LEVEL
#define BSP_DIGITAL_IO_INPUT_ACTIVE_LEVEL GPIO_PIN_RESET
#endif

#ifndef BSP_DIGITAL_IO_OUTPUT_ACTIVE_LEVEL
#define BSP_DIGITAL_IO_OUTPUT_ACTIVE_LEVEL GPIO_PIN_SET
#endif

typedef enum
{
  BSP_DIGITAL_IO_INPUT_1 = 0,
  BSP_DIGITAL_IO_INPUT_2,
  BSP_DIGITAL_IO_INPUT_3,
  BSP_DIGITAL_IO_INPUT_4,
  BSP_DIGITAL_IO_INPUT_5,
  BSP_DIGITAL_IO_INPUT_6,
  BSP_DIGITAL_IO_INPUT_7,
  BSP_DIGITAL_IO_INPUT_8,
  BSP_DIGITAL_IO_INPUT_COUNT
} BSP_DIGITAL_IO_Input;

typedef enum
{
  BSP_DIGITAL_IO_OUTPUT_RELAY_1 = 0,
  BSP_DIGITAL_IO_OUTPUT_RELAY_2,
  BSP_DIGITAL_IO_OUTPUT_RELAY_3,
  BSP_DIGITAL_IO_OUTPUT_RELAY_4,
  BSP_DIGITAL_IO_OUTPUT_TRANSISTOR_1,
  BSP_DIGITAL_IO_OUTPUT_TRANSISTOR_2,
  BSP_DIGITAL_IO_OUTPUT_TRANSISTOR_3,
  BSP_DIGITAL_IO_OUTPUT_TRANSISTOR_4,
  BSP_DIGITAL_IO_OUTPUT_COUNT
} BSP_DIGITAL_IO_Output;

void BSP_DIGITAL_IO_Init(void);
GPIO_PinState BSP_DIGITAL_IO_ReadInputRaw(BSP_DIGITAL_IO_Input input);
int BSP_DIGITAL_IO_ReadInputActive(BSP_DIGITAL_IO_Input input);
uint16_t BSP_DIGITAL_IO_ReadInputMask(void);
void BSP_DIGITAL_IO_SetOutput(BSP_DIGITAL_IO_Output output, int active);
int BSP_DIGITAL_IO_GetOutput(BSP_DIGITAL_IO_Output output);
void BSP_DIGITAL_IO_SetOutputMask(uint16_t active_mask);
uint16_t BSP_DIGITAL_IO_GetOutputMask(void);
void BSP_DIGITAL_IO_AllOutputsOff(void);

#endif /* BSP_DIGITAL_IO_H */
