#ifndef BSP_DIGITAL_IO_H
#define BSP_DIGITAL_IO_H

#include <stdint.h>

#include "board_pins.h"

#ifndef BSP_DIGITAL_IO_INPUT_ACTIVE_LEVEL
#define BSP_DIGITAL_IO_INPUT_ACTIVE_LEVEL GPIO_PIN_RESET
#endif

#ifndef BSP_DIGITAL_IO_OUTPUT_ACTIVE_LEVEL
#define BSP_DIGITAL_IO_OUTPUT_ACTIVE_LEVEL GPIO_PIN_SET
#endif

typedef enum
{
  BSP_DIGITAL_IO_INPUT_X1 = 0,
  BSP_DIGITAL_IO_INPUT_X2,
  BSP_DIGITAL_IO_INPUT_X3,
  BSP_DIGITAL_IO_INPUT_X4,
  BSP_DIGITAL_IO_INPUT_X5,
  BSP_DIGITAL_IO_INPUT_X6,
  BSP_DIGITAL_IO_INPUT_X7,
  BSP_DIGITAL_IO_INPUT_X8,
  BSP_DIGITAL_IO_INPUT_COUNT
} BSP_DIGITAL_IO_Input;

typedef enum
{
  BSP_DIGITAL_IO_OUTPUT_RELAY1 = 0,
  BSP_DIGITAL_IO_OUTPUT_RELAY2,
  BSP_DIGITAL_IO_OUTPUT_RELAY3,
  BSP_DIGITAL_IO_OUTPUT_RELAY4,
  BSP_DIGITAL_IO_OUTPUT_TRANSISTOR1,
  BSP_DIGITAL_IO_OUTPUT_TRANSISTOR2,
  BSP_DIGITAL_IO_OUTPUT_TRANSISTOR3,
  BSP_DIGITAL_IO_OUTPUT_TRANSISTOR4,
  BSP_DIGITAL_IO_OUTPUT_DO_I,
  BSP_DIGITAL_IO_OUTPUT_DO_U,
  BSP_DIGITAL_IO_OUTPUT_COUNT
} BSP_DIGITAL_IO_Output;

void BSP_DIGITAL_IO_Init(void);
GPIO_PinState BSP_DIGITAL_IO_ReadInputRaw(BSP_DIGITAL_IO_Input input);
int BSP_DIGITAL_IO_ReadInputActive(BSP_DIGITAL_IO_Input input);
uint16_t BSP_DIGITAL_IO_ReadInputMask(void);
void BSP_DIGITAL_IO_SetOutput(BSP_DIGITAL_IO_Output output, int active);
int BSP_DIGITAL_IO_GetOutput(BSP_DIGITAL_IO_Output output);
void BSP_DIGITAL_IO_SetOutputMask(uint16_t active_mask);
uint16_t BSP_DIGITAL_IO_GetOutputMask(void);
void BSP_DIGITAL_IO_AllOutputsOff(void);

#endif /* BSP_DIGITAL_IO_H */
